### ISSUE TITLE
Missing Prompts

### ISSUE THREAD

**Issue by Ber666** [thunlp/Intrinsic-Prompt-Tuning#1]
Hi, thanks for the great work! Could you please double check the pre-trained prompts you uploaded? I ran ISF-prompt with the random split and it turned out only 91 tasks have a prompt (9 prompts are missing). Not sure if I made some mistakes... Thanks for your time.
```
11/29/2022 23:00:29 - INFO - __main__ - found prompt in 91 tasks
11/29/2022 23:00:29 - INFO - __main__ - did not found prmopt in 9 tasks
```

**Comment by thuqinyj16** [comment]
Hi,

Thanks for your interest in our work! I've just uploaded the task split file (please check https://github.com/thunlp/Intrinsic-Prompt-Tuning/tree/master/dataloader/custom_tasks_splits_new/random.json). The original random.json file is outdated and not actually used in experiments. Feel free to ask any further questions.

**Comment by Ber666** [comment]
Hi, thanks for your quick reply, but I think the new version is the same as the old one...

**Comment by thuqinyj16** [comment]
Hi, could plz identify which tasks' prompts are missing? Probably I should upgrade the few_shot_prompt file

**Comment by thuqinyj16** [comment]
Also, please check whether the prompts from this would work. [ https://cloud.tsinghua.edu.cn/f/cf1ccb8a521743b28d4d/?dl=1 ]

**Comment by thuqinyj16** [comment]
Also, please check whether the prompts from this would work. [ https://cloud.tsinghua.edu.cn/f/cf1ccb8a521743b28d4d/?dl=1 ]

**Comment by Ber666** [comment]
The prompts from this new link work! Thanks.
